spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event-booking-db
    username: postgres
    password: asterisk
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/event_booking_mongo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false